init
taosdata/taos-connector-node pull request #51
Opened 2024-04-09 09:06 UTC by menshibin

2024-04-09 11:32 UTC, huskar-t commented on nodejs/src/client/wsClient.ts
> +    private _req_id = 1000000;
unsued

2024-04-09 11:32 UTC, huskar-t commented on nodejs/src/client/wsClient.ts
> +    private _url:URL;
readonly?

2024-04-09 11:34 UTC, huskar-t commented on nodejs/package.json
> +    "@types/websocket": "^1.0npm install async-mutex.5",
wrong version

2024-04-09 11:36 UTC, huskar-t commented on nodejs/src/common/reqid.ts
> +import { v4 as uuidv4 } from 'uuid';
uuid not found

2024-04-09 11:37 UTC, huskar-t commented on nodejs/src/common/taosResult.ts
> +    let decoder = new TextDecoder();
unused

2024-04-09 11:38 UTC, huskar-t commented on nodejs/src/common/wsError.ts
> +
Unnecessary semicolon

2024-04-09 11:38 UTC, huskar-t commented on nodejs/src/common/wsError.ts
> +    ERR_UNSPPORTED_TDENGINE_TYPE = 107,
typo? unsupported?

2024-04-09 11:39 UTC, huskar-t commented on nodejs/src/sql/wsRows.ts
> +            if (wsFetchResponse.completed == true) {
Can be simplified to wsFetchResponse.completed

2024-04-09 11:39 UTC, huskar-t commented on nodejs/src/sql/wsRows.ts
> +        if (this._taosResult.GetData() == null) {
'if' statement can be simplified

2024-04-09 11:40 UTC, huskar-t commented on nodejs/src/sql/wsSql.ts
> +                        if (wsFetchResponse.completed == true) {
Can be simplified to wsFetchResponse.completed

2024-04-09 11:40 UTC, huskar-t commented on nodejs/src/sql/wsSql.ts
> +                    this._wsClient.freeResult(wsQueryResponse)
Missing await for an async function call ?

2024-04-09 11:41 UTC, huskar-t commented on nodejs/src/tmq/config.ts
> +    clien_id: string;
typo?

2024-04-10 01:22 UTC, huskar-t commented on nodejs/src/tmq/tmqResponse.ts
> +export class CommitedResp extends PartitionsResp {
typo?

2024-04-10 01:22 UTC, huskar-t commented on nodejs/src/tmq/wsTmq.ts
> +                if (pollResp.have_message == false || pollResp.message_type != TMQMessageType.ResDataType) {
Can be simplified to !pollResp.have_message

2024-04-10 01:23 UTC, huskar-t commented on nodejs/src/tmq/wsTmq.ts
> +                            let currTime = new Date().getTime();
unused

2024-04-10 01:24 UTC, huskar-t commented on nodejs/src/client/wsConnectorPool.ts
> +    private  _maxConnections: number;
readonly?

2024-04-10 01:31 UTC, huskar-t commented on nodejs/src/sql/wsRows.ts
> +        this._wsClient.freeResult(this._wsQueryResponse)
need .then()?

2024-04-10 01:32 UTC, huskar-t commented on nodejs/src/sql/wsRows.ts
> +    private _wsQueryResponse: WSQueryResponse;
readonly?

2024-04-10 01:34 UTC, huskar-t commented on nodejs/example/basicSql.ts
> +        await wsRows.Close()
wrRows.Close is a synchronous function

2024-04-10 01:35 UTC, huskar-t commented on nodejs/src/sql/wsSql.ts
> +                            taosResult = tmp;
is redundant

2024-04-10 01:36 UTC, huskar-t commented on nodejs/src/stmt/wsParams.ts
> +    private _params: ColumnInfo[];
readonly?

2024-04-10 01:39 UTC, huskar-t requested changes
see my comments

2024-04-10 02:21 UTC, huskar-t commented on nodejs/src/common/taosResult.ts
> +    public  AddtotalTime(totalTime:number) {
AddtotalTime -> AddTotalTime

2024-04-10 02:31 UTC, huskar-t commented
need to format and add automatic tests

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/example/basicSchemaless.ts
> +let influxdbData = "st,t1=3i64,t2=4f64,t3=\"t3\" c1=3i64,c3=L\"passit\",c2=false,c4=4f64 1626006833639000000";
尽量使用 meters 表做用例

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/example/basicSql.ts
> +let dsn = 'ws://root:taosdata@192.168.1.95:6051/ws';
最后的 ws 是数据库吗，如果不是，是端点，不要体现出来，Adapter 的 路径对外不可见

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/example/basicTmq.ts
> +    [TMQConstants.WS_URL, 'ws://192.168.1.95:6051/rest/tmq'],
rest/tmq 不要暴露

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/readme.md
> +
dsn 定义是对的，严格按照这个来解析

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/readme.md
> +let dsn = "ws://host:port/rest/ws/db"
这里跟上面 dsn 对不上

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/client/wsClient.ts
> +                console.log("ready status ", this._url, this._wsConnector.readyState())
库的代码 不能调用 console log， 这种应该 类似 与 system print，性能很低。请采用日志库，安装日志级别打印合适的信息

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/client/wsClient.ts
> +                    resolve(parseBlock(fetchResponse.rows, new WSFetchBlockResponse(resp.msg), taosResult));
可以分开多行写，否则这里很难调试

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/client/wsClient.ts
> +    // private getReqID() {
无用代码删除

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/client/wsConnector.ts
> +        } else if (Object.prototype.toString.call(data) === '[object Blob]') {
有没有更优雅的类型比较方式？

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/client/wsConnector.ts
> +        if (msg.args.id !== undefined) {
这个判断是否反了？另外不建议再去解析json了，这里只管发送，赋值是上层的事儿

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/common/ut8Helper.ts
> +// Numbers fundamental to the encoding.
这个文件是做什么的，是不是应该叫 utf8Helper

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/sql/wsSql.ts
> +    async execute(sql: string, reqId?: number, action:string = 'query'): Promise<TaosResult> {
schemaless 不支持sql

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/stmt/wsParams.ts
> +    private encodeColumnNumbers(params:any[], dataType:string = 'number', typeLen:number, columnType:number):[number, ArrayBuffer] {
方法名好像只处理 number 类型

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/src/tmq/wsTmq.ts
> +                        // count++
无用代码都应该删除，不要注释掉

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/test/bulkPulling/queryTables.test.ts
> +                        expect(d).toBeTruthy()
为何这两种类型没有仔细检查？

2024-04-10 02:49 UTC, sheyanjie-qq commented on nodejs/test/bulkPulling/schemaless.test.ts
> +    test('normal wsSql insert', async() => {
这里都没有check

2024-04-18 05:09 UTC, merged